#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages,


echo -e "install nginx"
sudo apt-get -y install nginx

#starting the server
sudo service nginx start

# allowing firewall
sudo ufw allow 'Nginx HTTP'

# give the user 
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www


echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart

